# Logging Configuration (set org.sitmun or org.sitmun.proxy.middleware via env, e.g. Docker)
logging:
  level:
    ROOT: INFO

# Sitmun Proxy Configuration
sitmun:
  backend:
    config:
      url: http://some.url
      secret: ${SITMUN_BACKEND_CONFIG_SECRET}
  ogc:
    capabilities:
      service-paths:
        - wms
        - wfs
        - wcs
        - ows
      extra-sources: []

# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health
      base-path: /actuator
  endpoint:
    health:
      show-details: never
      show-components: never
  health:
    defaults:
      enabled: true